# Generated by Django 5.2.3 on 2025-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('lessons_count', models.IntegerField()),
                ('tutor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
