# Generated by Django 5.2.3 on 2025-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.FilePathField(match='.*\\.(jpg|png|jpeg)$', max_length=200, path='static/home/images/', recursive=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lessons_count',
            field=models.CharField(max_length=20),
        ),
    ]
