# Generated by Django 5.2.3 on 2025-06-24 14:18

import home.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_courses_image_alter_courses_lessons_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=home.models.StaticImageField(upload_to=''),
        ),
    ]
