# Generated by Django 5.2.3 on 2025-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_courses_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicrelations',
            options={'verbose_name': 'Public Relation', 'verbose_name_plural': 'Public Relations'},
        ),
        migrations.AddField(
            model_name='courses',
            name='relative_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lessons_count',
            field=models.CharField(max_length=20),
        ),
    ]
