# Generated by Django 5.2.3 on 2025-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_publicrelations_options_courses_relative_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='relative_url',
        ),
    ]
